[ui]
username = Siming Feng <sfeng@roblox.com>
merge = :merge3

[isl]
submitAsDraft = true
render-compact = false

[auth]
ghcli.clientpath = /opt/homebrew/bin/gh

[github]
preferred_submit_command = pr
pr-workflow = single
preserve-pull-request-description = true
pull-request-include-reviewstack = false
pr.branch-name-template = {ifeq(lower(sub(r':.*','',strip(firstline(desc)))),'adhoc','adhoc',ifeq(lower(sub(r':.*','',strip(firstline(desc)))),'bugfix','bugfix','feature'))}/{ifeq(lower(sub(r':.*','',strip(firstline(desc)))),'adhoc','',ifeq(lower(sub(r':.*','',strip(firstline(desc)))),'bugfix','',sub(r':.*$','-',strip(firstline(desc)))))}{sub(r'\W+','-',lower(sub(r'^[^:]*:\s*','',strip(firstline(desc)))))}-sfeng-pr{github_pull_request_number}
