[[themes]]
name = "rose_pine"

[themes.palette]
background = "#191724"  # base
foreground = "#e0def4"  # text

[themes.component_style]
block_title         = { fg = "#c4a7e7", modifiers = ["Bold"] }                # iris (lavender)
border              = { fg = "#6e6a86" }                                      # muted (gray)
playback_status     = { fg = "#9ccfd8", modifiers = ["Bold"] }                # foam (light blue)
playback_track      = { fg = "#f6c177", modifiers = ["Bold"] }                # gold
playback_artists    = { fg = "#ebbcba" }                                      # rose
playback_album      = { fg = "#c4a7e7" }                                      # iris (lavender)
playback_genres     = { fg = "#908caa" }                                      # subtle (light gray)
playback_metadata   = { fg = "#6e6a86" }                                      # muted (gray)
playback_progress_bar          = { fg = "#c4a7e7", bg = "#26233a" }           # iris (lavender) on overlay (dark gray)
playback_progress_bar_unfilled = { bg = "#26233a" }                           # overlay (dark gray)
current_playing     = { fg = "#f6c177", modifiers = ["Bold"] }                # gold
page_desc           = { fg = "#ebbcba", modifiers = ["Bold"] }                # rose
playlist_desc       = { fg = "#908caa" }                                      # subtle (light gray)
table_header        = { fg = "#ebbcba", modifiers = ["Bold"] }                # rose
selection           = { bg = "#26233a", modifiers = ["Bold"] }                # overlay (dark gray)
secondary_row       = { fg = "#908caa" }                                      # subtle (light gray)
like                = { fg = "#eb6f92" }                                      # love (pink)
lyrics_played       = { fg = "#6e6a86" }                                      # muted (gray)
lyrics_playing      = { fg = "#f6c177", modifiers = ["Bold"] }                # gold
